### ISSUE TITLE
change out of window 

### ISSUE THREAD

**Issue by andrewgremlich** [byuicampuscd/function-machine#26]
change out of window error similar to the out of domain error

**Comment by andrewgremlich** [comment]
and red

**Comment by andrewgremlich** [comment]
I fixed the error handling, so now the styling...

**Comment by andrewgremlich** [comment]
I don't think red is going to work...

**Comment by andrewgremlich** [comment]
With the dark grey background at least.

**Comment by andrewgremlich** [comment]
I swapped out the dark grey background for a light grey background in GIMP and now the red text works.

**Comment by meeple142** [comment]
great!

Joshua McKinney
Campus Curriculum Developer
Brigham Young University - Idaho
Lamprecht Hall 203B
208-496-1534

On Tue, Oct 25, 2016 at 10:07 AM -0600, "Andrew Gremlich" <notifications@github.com<mailto:notifications@github.com>> wrote:

I swapped out the dark grey background for a light grey background in GIMP and now the red text works.

##
