### ISSUE TITLE
Title & Instructions

### ISSUE THREAD

**Issue by andrewgremlich** [byuicampuscd/function-machine#4]
Add in a title and instructions for the application.

**Comment by andrewgremlich** [comment]
I don't see a good graphical use to have the title and instructions be on screen all the time.  I think it would be better if the title and instructions were contained in something like a modal popup.

**Comment by meeple142** [comment]
No just let people scroll down no need to complicate it.

Get Outlook for Androidhttps://aka.ms/ghei36

**Comment by andrewgremlich** [comment]
I had designers looked at it and made the case not to have the text on top.  The design of the machine will flow better with out the text.

**Comment by andrewgremlich** [comment]
There will be a pop up.

**Comment by andrewgremlich** [comment]
Done!
