### ISSUE TITLE
Hide Equation

### ISSUE THREAD

**Issue by andrewgremlich** [byuicampuscd/function-machine#9]
Hide the equation option

**Comment by andrewgremlich** [comment]
Feature added!

**Comment by meeple142** [comment]
What did you type into the function equation location when missing?

**Comment by andrewgremlich** [comment]
To make it missing?  I just had an "hideEquation" name with a boolean value in the settings.
@meeple142

**Comment by andrewgremlich** [comment]
The equation reappears when going along the promise chain...

**Comment by meeple142** [comment]
They wanted text in the machine, something like "mystery equation" instead of y=x+2

**Comment by andrewgremlich** [comment]
Oh yeah I'll get on that.

**Comment by andrewgremlich** [comment]
Good to go!
